###
# ESP settings
###
esp32:
  board: esp32dev
  framework:
    type: arduino
    
###
# Uart Settings
###
uart:
  id:          uart_modbus
  tx_pin:      19
  rx_pin:      22
  baud_rate:   19200
  data_bits:   8
  stop_bits:   1
  parity:      EVEN
  debug:
    direction: BOTH
