###
# Modbus Settings
###
modbus:
  id: modbuswtw
  uart_id: uart_modbus
  #send_wait_time: 2000ms

modbus_controller:
  - id: wtw
    address:          72
    modbus_id:        modbuswtw
    setup_priority:   -10
    update_interval:  15s
    command_throttle: 200ms
    offline_skip_updates: 100

substitutions:
  skip_updates: "5"
  skip_updates_errors: "10"
  skip_updates_advanced: "100"
  modbus_id: wtw
  max_cap: "399"
  flap_max: "550"
  alert_icon: mdi:alert-circle
  max_error_number: "5"
